# Generated by Django 5.1.6 on 2025-02-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Комментарий', to='Base.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Лайки', to='Base.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='reaction',
            field=models.IntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Пост', to='Base.category'),
        ),
    ]
